import {
  PLANET_LABELS,
  type DiagnosticDraft,
  type LeadPriority,
  type StructuredBrief,
} from "./contracts.ts";

export function calculatePriority(draft: DiagnosticDraft, now = new Date()): LeadPriority {
  const urgentProcurement = /approved|rfp|delivery|in.progress|live|production/i.test(draft.delivery.procurementState);
  const urgentInitiative = /delivery|live|production|improvement|in.progress/i.test(draft.currentState.initiativeStage);
  const timeline = draft.delivery.timeline.replace(/[_–—]/g, "-");
  if (/0\s*-\s*4\s*week/i.test(timeline) && (urgentProcurement || urgentInitiative)) return "URGENT";
  if (/1\s*-\s*3\s*month/i.test(timeline)) return "HIGH";

  if (draft.delivery.targetDate) {
    const milliseconds = new Date(`${draft.delivery.targetDate}T23:59:59.999Z`).getTime() - now.getTime();
    if (milliseconds >= 0 && milliseconds <= 90 * 24 * 60 * 60 * 1000) return "HIGH";
  }
  return "NORMAL";
}

export function generateBrief(
  draft: DiagnosticDraft,
  referenceCode: string,
  generatedAt: string,
): StructuredBrief {
  const clarifications = Object.entries(draft.technicalSignals.systemAnswers)
    .filter(([, answer]) => /not[ _-]?sure/i.test(answer ?? ""))
    .map(([system]) => `${PLANET_LABELS[system as keyof typeof PLANET_LABELS]} technical signals`);
  if (/not[ _-]?sure/i.test(draft.technicalSignals.regulatedData)) clarifications.unshift("Regulated data exposure");

  const budget = draft.delivery.budget
    ? `${draft.delivery.budget.currency} ${draft.delivery.budget.band}`
    : "Not disclosed";

  return {
    version: "RULES_V1",
    referenceCode,
    headline: `${PLANET_LABELS[draft.primarySystem]} initiative for ${draft.contact.company}`,
    systems: draft.systems.map((id) => ({ id, label: PLANET_LABELS[id], primary: id === draft.primarySystem })),
    project: {
      goal: draft.outcome.objective,
      desiredOutcomes: draft.outcome.expectedOutcomes,
      executiveSummary: draft.outcome.executiveSummary,
      initiativeStage: draft.currentState.initiativeStage,
      deliveryContext: draft.currentState.deliveryContext,
      impactScope: draft.currentState.impactScope,
      currentLandscape: draft.currentState.landscape,
      dependencies: draft.currentState.dependencies,
    },
    technical: {
      domains: draft.technicalSignals.domains,
      deploymentMode: draft.technicalSignals.deploymentMode,
      regulatedData: draft.technicalSignals.regulatedData,
      complianceFrameworks: draft.technicalSignals.complianceFrameworks,
      clarifications,
    },
    delivery: {
      engagementModel: draft.delivery.engagementModel,
      procurementState: draft.delivery.procurementState,
      timeframe: draft.delivery.timeline,
      ...(draft.delivery.targetDate ? { targetDate: draft.delivery.targetDate } : {}),
      budget,
    },
    contact: {
      name: draft.contact.fullName,
      title: draft.contact.jobTitle,
      company: draft.contact.company,
      workEmail: draft.contact.workEmail,
      phone: draft.contact.phone,
      country: draft.contact.country,
    },
    generatedAt,
  };
}

export function renderBriefText(brief: StructuredBrief): string {
  const systems = brief.systems.map((system) => `${system.primary ? "PRIMARY — " : ""}${system.label}`).join("; ");
  const clarifications = brief.technical.clarifications.length ? brief.technical.clarifications.join("; ") : "None recorded";
  return [
    `PROJECT BRIEF ${brief.referenceCode}`,
    brief.headline,
    "",
    `Systems: ${systems}`,
    `Goal: ${brief.project.goal}`,
    `Desired outcomes: ${brief.project.desiredOutcomes.join("; ")}`,
    `Executive summary: ${brief.project.executiveSummary}`,
    `Current landscape: ${brief.project.currentLandscape}`,
    `Delivery: ${brief.delivery.engagementModel}; ${brief.delivery.timeframe}; ${brief.delivery.budget}`,
    `Clarify in discovery: ${clarifications}`,
    `Contact: ${brief.contact.name}, ${brief.contact.title}, ${brief.contact.company} — ${brief.contact.workEmail}`,
    "",
    "Generated by e Gain deterministic brief rules (RULES_V1).",
  ].join("\n");
}
